### ISSUE TITLE
한줄 추가

### ISSUE THREAD

**Issue by SCPJaehyeon** [choikongji/sum_test#1]
https://github.com/choikongji/sum_test/commit/332aabf80bb8c2b4b0b7dbb70f68565f585be7ab#r37988404

**Comment by choikongji** [comment]
done in https://github.com/choikongji/sum_test/commit/509acd0cf6fa878f6dd9b58b57292310d43d9365

**Comment by SCPJaehyeon** [comment]
수고하셨습니다~
